pipeline:
  identifier: Build_harness_cie_lab_1706790246851
  name: Sujoy_First_Pipeline
  orgIdentifier: workshoptcscoe74org
  projectIdentifier: Sujoy_Test_Harness
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.workshopgithub
        repoName: harness-cie-lab
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: RunTests
                  name: RunTests_1
                  identifier: RunTests_1
                  spec:
                    connectorRef: account.bootcampdockerhub
                    image: nikpap/mvn-openjdk-8:harness
                    language: Java
                    buildTool: Maven
                    args: clean test
                    packages: com.nikp
                    runOnlySelectedTests: true
                    preCommand: cd payment-service
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    resources:
                      limits:
                        memory: 2GI
                        cpu: "2"
                    enableTestSplitting: false
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    connectorRef: account.bootcampdockerhub
                    image: nikpap/mvn-openjdk-8:harness
                    shell: Sh
                    command: |
                      cd payment-service
                      mvn -Dmaven.test.skip=true clean install -X
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: "1"
              - step:
                  type: Security
                  spec:
                    privileged: true
                    settings:
                      product_name: fortify
                      product_config_name: fortify-default
                      policy_type: manualUpload
                      scan_type: repository
                      repository_project: payment-service
                      repository_branch: <+codebase.branch>
                      customer_artifacts_path: sto_tests/scan_tools/fortify/test_data
                      manual_upload_filename: "001"
                    imagePullPolicy: Always
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: ManualIntervention
                          spec:
                            timeout: 1d
                            onTimeout:
                              action:
                                type: StageRollback
                  when:
                    stageStatus: Success
                  name: Fortify
                  identifier: Fortify
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.bootcampdockerhub
                    repo: nikpap/payment-service-workshop
                    tags:
                      - sujoybanerjee-latest
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: "1"
              - step:
                  type: Owasp
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      name: <+pipeline.name>
                      variant: <+codebase.branch>
                    advanced:
                      log:
                        level: info
                  name: OWSAP
                  identifier: OWSAP
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.bootcampgkecluster
              namespace: payment-service-build
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
  tags: {}
