pipeline:
  identifier: Build_harness_cie_lab_1710411484401
  name: Build harness-cie-lab
  orgIdentifier: workshoptcscoe106org
  projectIdentifier: samit
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.workshopgithub
        repoName: harness-cie-lab
  stages:
    - stage:
        identifier: build
        name: build and run
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      password: <+input>
                      repo: hello/world
                      tags: latest
                      username: <+input>
                  timeout: ""
                  type: Plugin
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec: {}
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
        type: CI
        description: ""
