pipeline:
  identifier: Build_harness_cie_lab_1706790542479
  name: Build harness-cie-lab
  orgIdentifier: workshoptcscoe74org
  projectIdentifier: TCSPrajakta
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.workshopgithub
        repoName: harness-cie-lab
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run
                  identifier: Run
                  spec:
                    connectorRef: account.bootcampdockerhub
                    image: nikpap/mvn-openjdk-8:harness
                    shell: Sh
                    command: cd payment-service
                    privileged: false
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: "2"
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    connectorRef: account.bootcampdockerhub
                    image: nikpap/mvn-openjdk-8:harness
                    shell: Sh
                    command: |-
                      cd payment-service
                      mvn -Dmaven.test.skip=true clean install -X
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: "1"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Push to DockerHub
                  identifier: Push_to_DockerHub
                  spec:
                    connectorRef: account.bootcampdockerhub
                    repo: nikpap/payment-service-workshop
                    tags:
                      - prajakta-latest
                    optimize: true
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: "1"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.bootcampgkecluster
              namespace: payment-service-build
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
