pipeline:
  name: payment-service
  identifier: Build_harness_cie_lab_1702984481749
  projectIdentifier: ryanlab
  orgIdentifier: handsonlab55org
  stages:
    - stage:
        name: Build and Push
        identifier: Build_and_Push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.bootcampgkecluster
              namespace: payment-service-build
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: RunTests
                  name: Run Tests
                  identifier: Run_Tests
                  spec:
                    connectorRef: account.bootcampdockerhub
                    image: nikpap/mvn-openjdk-8:harness
                    language: Java
                    buildTool: Maven
                    args: test
                    packages: com.nikp
                    runOnlySelectedTests: true
                    preCommand: cd payment-service
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: "2"
                    enableTestSplitting: false
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    connectorRef: account.bootcampdockerhub
                    image: nikpap/mvn-openjdk-8:harness
                    shell: Sh
                    command: |-
                      cd payment-service

                      mvn -Dmaven.test.skip=true clean install -X
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: "1"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.bootcampdockerhub
                    repo: nikpap/payment-service-workshop
                    tags:
                      - ryanlab-latest
                    optimize: true
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: "1"
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.workshopgithub
        repoName: harness-cie-lab
        build: <+input>
